name: Build ZMK firmware

on:
  push:
    branches:
      - main
      - fix/**   # ← fix/auto-mouse-stop を含め、fix系ブランチを対象にする
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ZMK firmware
        uses: zmkfirmware/zmk-docker-build@main
        with:
          build-yaml: build.yaml

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zmk-firmware
          path: build/artifacts/**
